version: "3.9"

services:
  
  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - /app/node_modules
      - ./:/app
    restart: "unless-stopped"

