FROM node:20-buster-slim

# Work to Dir
WORKDIR /app

COPY package.json /app/package.json

# Install Node Package
RUN npm install

RUN npm i -g prisma

# Copy Dir
COPY . .

RUN chmod +x entrypoint-dev.sh

# Set Env
ENV NODE_ENV development

EXPOSE 3001

# Cmd script
CMD ["./entrypoint-dev.sh"]