# NodeJS Version 16
FROM node:20-buster-slim

WORKDIR /app

COPY package.json /app/package.json

# Install Node Package
RUN npm install

RUN npm i -g prisma

# Copy Dir
COPY . .

RUN chmod +x entrypoint-prod.sh

# Set Env
ENV NODE_ENV production

EXPOSE 3001

# Cmd script
CMD ["./entrypoint-prod.sh"]