FROM node:20-buster-slim

# Copy Dir
COPY . ./app

# Work to Dir
WORKDIR /app

# Install Node Package
RUN npm install

RUN npm i -g prisma

RUN chmod +x entrypoint-dev.sh

# Set Env
ENV NODE_ENV development

EXPOSE 3001

# Cmd script
CMD ["./entrypoint-dev.sh"]